# Service for ECM Identity Service
apiVersion: v1
kind: Service
metadata:
  name: ecm-identity-service
spec:
  type: ClusterIP
  selector:
    app: ecm-identity-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
