# Kustomize overlay for UAT environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ecm-identity-service-uat

namespace: ecm-identity-uat

commonLabels:
  environment: uat

resources:
- ../../base

patches:
- path: configmap-patch.yaml

images:
- name: ecm-identity-service
  newName: ecm-identity-service
  newTag: uat-latest

replicas:
- name: ecm-identity-service
  count: 2
