# Kustomize overlay for STAGING environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ecm-identity-service-staging

namespace: ecm-identity-staging

commonLabels:
  environment: staging

resources:
- ../../base

patches:
- path: configmap-patch.yaml

images:
- name: ecm-identity-service
  newName: ecm-identity-service
  newTag: staging-latest

replicas:
- name: ecm-identity-service
  count: 2
